= Installation & Operators

== Installation

For the lab portion of this training, the Openshift environment is already pre-provisioned, which unfortunately skips a major hurdle which is encountered as part of these Proof of Concept deliveries.  As many of you are aware, there's several different ways to deploy Openshift at a customer site.  The two methods that we have found the most success with both utilizae the Assisted Installer:

* Interactive Assisted Installer
* Local Agent Installer

We estimate 99% of the deployments we do for a Proof of Concept utilize the Interactive Assisted Installer where the customer is walked through the process of configuring the cluster, booting the bare-metal machines and deploying the cluster. When this method is not feasible due to connectivity, we fallback to a Local Agent Installer using a Local/Disconnected Registry. See xref:22_disconnected.adoc[Disconnected Environments] for more details on this type of deployment method.


== Operators

During installation, you have the option to include various Operators as part of the deployment process.  Deployment of Operators is something that is second nature for those familiar with Openshift, however, for many of the customers coming from other Virtualization Platforms this concept is new.  Due to this reason, many times we choose not to install the Operators at Deployment Time.

For your lab environment, these will be pre-installed in an effort to save time, however, this section will cover the Operators that we typically install and configure as part of the Proof of Concept delivery and how they are typically configured.

[[storage_operator]]
=== Openshift Storage
For Proof of Concept deployments, we try to position ODF backed by Ceph as the solution of choice as this has several advantages over other CSI Backed Storage Options thanks to Ceph's Copy on Write feature.

* Virtual Machines start almost instantly
* Storage space is saved for VM's using the same Image Base

Additionally, this is "most like" VMWare environments where the customers are utilizing VSAN as the back-end storage.

When we deploy this via the Operator, we use the default settings for the deployment.

[[virtualization_operator]]
=== Openshift Virtualization
Sometimes customers would like to utilize a dedicated migration network when live migrations are performed.  This can be configured when installing the Openshift Virtualization Operator, or it may also be configured after deployment.

Ensure that you create the *Network Attachment Definition* prior to configuring this.

Other than that, when we deploy this via the Operator, we use the default settings for the deployment.

[[nmstate_operator]]
=== NMState Operator
The NMState Operator

This will give us the *NodeNetworkConfigurationPolicy* link in the Console UI.

When we deploy this via the Operator, we use the default settings for the deployment.

[[mtv_operator]]
=== Openshift Migration Toolkit for Virtualization
When we deploy this via the Operator, we use the default settings for the deployment.